language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - mysql -e 'create database timeplanner;'

install: ant -logger org.apache.tools.ant.NoBannerLogger initialize

script: ant -logger org.apache.tools.ant.NoBannerLogger test

cache:
    directories:
        - vendor
