language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

services:
    - couchdb

before_script:
    - curl -X PUT localhost:5984/timeplanner

install: ant -logger org.apache.tools.ant.NoBannerLogger initialize

script: ant -logger org.apache.tools.ant.NoBannerLogger test

cache:
    directories:
        - vendor
