language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 5.6 # https://github.com/doctrine/couchdb-odm/issues/108
        - php: 7.0 # https://github.com/doctrine/couchdb-odm/issues/108

services:
    - couchdb

script: ant -logger org.apache.tools.ant.NoBannerLogger test

cache:
    directories:
        - vendor
