language: php

php:
    - 5.6
    - 7.0
    - 7.1

services:
    - couchdb

install:
    - composer install
    - ant -logger org.apache.tools.ant.NoBannerLogger prepare

script: ant -logger org.apache.tools.ant.NoBannerLogger test
