language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

services:
    - couchdb

install: ant -logger org.apache.tools.ant.NoBannerLogger prepare

script: ant -logger org.apache.tools.ant.NoBannerLogger test
