doctrine_couch_db:
    client:
        host:     %database.host%
        port:     %database.port%
        dbname:   %database.name%
        user:     %database.user%
        password: %database.password%
    odm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            QafooUserBundle:
                prefix: 'Qafoo\UserBundle\Domain'
            QafooTimePlannerBundle:
                prefix: 'Qafoo\TimePlannerBundle\Domain'

doctrine:
    dbal:
        connections:
            default:
                driver:   %database.driver%
                host:     %database.host%
                port:     %database.port%
                dbname:   %database.name%
                path:     %database.path%
                user:     %database.user%
                password: %database.password%
                charset:  "UTF8"
    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        mappings:
            QafooUserBundle:
                prefix: 'Qafoo\UserBundle\Domain'
            QafooTimePlannerBundle:
                prefix: 'Qafoo\TimePlannerBundle\Domain'

fos_user:
    db_driver: %database.mapping%
    firewall_name: main
    user_class: Qafoo\UserBundle\Domain\FOSUser
    profile:
        form:
            type: qafoo_user_profile
    service:
        user_manager: qafoo.user.domain.user_service
