security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        qafoo_user:
            id: qafoo.user.gateway.user

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: qafoo_user
                csrf_provider: form.csrf_provider
                login_path: /auth
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/auth$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/request$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
